import { NextResponse } from 'next/server';
import connectDB from '@/lib/mongodb';
import Product from '@/models/Product';

const sampleProducts = [
  // Today's Deals
  { name: 'boAt Airdopes 141 TWS Earbuds with 42H Playtime', description: 'Wireless earbuds with BEAST Mode for low latency gaming, IPX4 water resistance, and Type-C charging.', price: 1299, originalPrice: 4490, discount: 71, category: 'Electronics', subcategory: 'Deals', image: 'https://m.media-amazon.com/images/I/51Q+JytbfCL._SX679_.jpg', stock: 500, rating: 3.9, reviews: 89450, brand: 'boAt', features: ['42hr playback', 'BEAST Mode', 'IPX4', 'Type-C charging'], isActive: true, badge: "71% off" },
  { name: 'Fire-Boltt Phoenix Smart Watch 1.3" Display', description: 'Smart watch with SpO2 monitoring, heart rate tracker, and 7 days battery life.', price: 1499, originalPrice: 8999, discount: 83, category: 'Electronics', subcategory: 'Deals', image: 'https://m.media-amazon.com/images/I/61Iop+zPu8L._SX679_.jpg', stock: 300, rating: 4.0, reviews: 45230, brand: 'Fire-Boltt', features: ['SpO2', 'Heart Rate', '7 Days Battery'], isActive: true, badge: "83% off" },
  { name: 'JBL Flip 6 Portable Bluetooth Speaker IP67', description: 'Portable waterproof speaker with 12 hours of playtime and powerful JBL Original Pro Sound.', price: 9999, originalPrice: 14999, discount: 33, category: 'Electronics', subcategory: 'Deals', image: 'https://m.media-amazon.com/images/I/71r3e5L2bEL._SX679_.jpg', stock: 150, rating: 4.5, reviews: 8900, brand: 'JBL', features: ['IP67 Waterproof', '12hr Playback', 'PartyBoost'], isActive: true, badge: "33% off" },
  { name: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones', description: 'Industry-leading noise cancellation with Auto NC Optimizer and 30-hour battery life.', price: 26990, originalPrice: 34990, discount: 23, category: 'Electronics', subcategory: 'Deals', image: 'https://m.media-amazon.com/images/I/61+btxzpfDL._SX679_.jpg', stock: 100, rating: 4.6, reviews: 5420, brand: 'Sony', features: ['30hr battery', 'Multi-device', 'Speak-to-Chat', 'LDAC'], isActive: true, badge: "23% off" },
  { name: 'Philips Air Fryer HD9200/90 - Uses up to 90% Less Fat', description: 'Rapid Air Technology for healthier cooking with up to 90% less fat.', price: 6999, originalPrice: 9995, discount: 30, category: 'Home & Kitchen', subcategory: 'Deals', image: 'https://m.media-amazon.com/images/I/51Y29MZbq4L._SX679_.jpg', stock: 200, rating: 4.4, reviews: 21340, brand: 'Philips', features: ['Rapid Air', '0.8kg capacity', 'Easy clean'], isActive: true, badge: "30% off" },
  { name: 'Noise ColorFit Pro 5 Smart Watch AMOLED Display', description: 'Smart watch with 1.85" AMOLED display, Bluetooth calling, and 7-day battery.', price: 3999, originalPrice: 7999, discount: 50, category: 'Electronics', subcategory: 'Deals', image: 'https://m.media-amazon.com/images/I/61RJZynP6TL._SX679_.jpg', stock: 250, rating: 4.1, reviews: 18900, brand: 'Noise', features: ['AMOLED', 'BT Calling', '100+ Sports'], isActive: true, badge: "50% off" },
  { name: 'Prestige Iris 750W Mixer Grinder 3 Jars', description: 'Powerful mixer grinder with 3 stainless steel jars and motor overload protection.', price: 3299, originalPrice: 5495, discount: 40, category: 'Home & Kitchen', subcategory: 'Deals', image: 'https://m.media-amazon.com/images/I/51R4x0CzKIL._SX679_.jpg', stock: 180, rating: 4.2, reviews: 34560, brand: 'Prestige', features: ['750W Motor', '3 Jars', 'Overload Protection'], isActive: true, badge: "40% off" },
  { name: 'Instant Pot Duo 7-in-1 Electric Pressure Cooker', description: 'Multi-use programmable pressure cooker, slow cooker, rice cooker, steamer, and more.', price: 8999, originalPrice: 12999, discount: 31, category: 'Home & Kitchen', subcategory: 'Deals', image: 'https://m.media-amazon.com/images/I/71V1LrY1MSL._SX679_.jpg', stock: 80, rating: 4.5, reviews: 23450, brand: 'Instant Pot', features: ['7-in-1', '6 Quart', 'Smart Programs'], isActive: true, badge: "31% off" },

  // Mobile Phones
  { name: 'Apple iPhone 15 Pro Max (256GB) - Natural Titanium', description: 'iPhone 15 Pro Max with A17 Pro chip, 48MP camera system, and titanium design.', price: 159900, originalPrice: 179900, discount: 11, category: 'Electronics', subcategory: 'Mobiles', image: 'https://m.media-amazon.com/images/I/81SigpJN1KL._SX679_.jpg', stock: 50, rating: 4.5, reviews: 2340, brand: 'Apple', features: ['A17 Pro chip', '48MP camera', 'Titanium', 'USB-C'], isActive: true },
  { name: 'Samsung Galaxy S24 Ultra 5G AI Smartphone', description: 'Galaxy AI smartphone with 200MP camera, S Pen, and Snapdragon 8 Gen 3 processor.', price: 129999, originalPrice: 144999, discount: 10, category: 'Electronics', subcategory: 'Mobiles', image: 'https://m.media-amazon.com/images/I/71WcEhL7qrL._SX679_.jpg', stock: 75, rating: 4.3, reviews: 1850, brand: 'Samsung', features: ['Galaxy AI', '200MP', 'S Pen', 'Snapdragon 8 Gen 3'], isActive: true },
  { name: 'OnePlus 12 5G (16GB RAM, 512GB Storage)', description: 'Flagship killer with Snapdragon 8 Gen 3, Hasselblad camera, and 100W charging.', price: 69999, originalPrice: 74999, discount: 7, category: 'Electronics', subcategory: 'Mobiles', image: 'https://m.media-amazon.com/images/I/71nYM8LSLBL._SX679_.jpg', stock: 120, rating: 4.4, reviews: 3200, brand: 'OnePlus', features: ['16GB RAM', '100W Charging', 'Hasselblad'], isActive: true },
  { name: 'iPhone 15 (128GB) - Blue', description: 'iPhone 15 with Dynamic Island, 48MP camera, and A16 Bionic chip.', price: 79900, originalPrice: 79900, discount: 0, category: 'Electronics', subcategory: 'Mobiles', image: 'https://m.media-amazon.com/images/I/71d7rfSl0wL._SX679_.jpg', stock: 90, rating: 4.6, reviews: 4500, brand: 'Apple', features: ['Dynamic Island', '48MP', 'A16 Bionic'], isActive: true },
  { name: 'Google Pixel 8 Pro (12GB RAM, 256GB)', description: 'Google Tensor G3 chip with advanced AI features and best-in-class camera.', price: 99999, originalPrice: 106999, discount: 7, category: 'Electronics', subcategory: 'Mobiles', image: 'https://m.media-amazon.com/images/I/71LFgCk-XpL._SX679_.jpg', stock: 60, rating: 4.5, reviews: 980, brand: 'Google', features: ['Tensor G3', '50MP', '7 Years Updates'], isActive: true },
  { name: 'Redmi Note 13 Pro+ 5G (12GB RAM, 512GB)', description: '200MP camera phone with 120W HyperCharge and 120Hz AMOLED display.', price: 32999, originalPrice: 36999, discount: 11, category: 'Electronics', subcategory: 'Mobiles', image: 'https://m.media-amazon.com/images/I/51tQJ5oylKL._SX679_.jpg', stock: 200, rating: 4.1, reviews: 5670, brand: 'Redmi', features: ['200MP', '120W Charge', '120Hz AMOLED'], isActive: true },
  { name: 'Nothing Phone (2a) (8GB RAM, 128GB)', description: 'Unique Glyph Interface with MediaTek Dimensity 7200 Pro and dual cameras.', price: 23999, originalPrice: 27999, discount: 14, category: 'Electronics', subcategory: 'Mobiles', image: 'https://m.media-amazon.com/images/I/61eBuA1DRSL._SX679_.jpg', stock: 150, rating: 4.3, reviews: 2340, brand: 'Nothing', features: ['Glyph Interface', '50MP', '45W Charging'], isActive: true },
  { name: 'Samsung Galaxy S23 FE 5G (8GB, 128GB)', description: 'Fan Edition flagship with Exynos 2200, 50MP camera, and IP68 rating.', price: 39999, originalPrice: 59999, discount: 33, category: 'Electronics', subcategory: 'Mobiles', image: 'https://m.media-amazon.com/images/I/41pWADM7lIL._SX679_.jpg', stock: 100, rating: 4.2, reviews: 2100, brand: 'Samsung', features: ['Exynos 2200', '50MP', 'IP68'], isActive: true },

  // Fashion
  { name: 'Nike Air Max 270 Running Shoes for Men', description: 'Max Air cushioning delivers all-day comfort with breathable mesh upper.', price: 9995, originalPrice: 13995, discount: 29, category: 'Fashion', subcategory: 'Footwear', image: 'https://m.media-amazon.com/images/I/71DUW2gU9uL._UX695_.jpg', stock: 150, rating: 4.2, reviews: 3420, brand: 'Nike', features: ['Air Max cushioning', 'Breathable mesh', 'Rubber outsole'], isActive: true },
  { name: "Levi's Men's 511 Slim Fit Jeans", description: 'Modern slim with room to move, sits below waist with slim fit through hip and thigh.', price: 2799, originalPrice: 3999, discount: 30, category: 'Fashion', subcategory: 'Jeans', image: 'https://m.media-amazon.com/images/I/71i0T-SU6QL._UY879_.jpg', stock: 200, rating: 4.1, reviews: 15670, brand: "Levi's", features: ['Slim fit', 'Stretch fabric', '5-pocket'], isActive: true },
  { name: 'Adidas Men Ultraboost Running Shoes', description: 'Responsive Boost midsole returns energy with every stride.', price: 12999, originalPrice: 19999, discount: 35, category: 'Fashion', subcategory: 'Footwear', image: 'https://m.media-amazon.com/images/I/71P-1TrOvzL._UX695_.jpg', stock: 120, rating: 4.5, reviews: 5670, brand: 'Adidas', features: ['Boost cushioning', 'Primeknit upper', 'Continental rubber'], isActive: true },
  { name: 'Fossil Gen 6 Smartwatch for Men', description: 'Smartwatch with Qualcomm 4100+, heart rate, SpO2, and Wear OS.', price: 19995, originalPrice: 29995, discount: 33, category: 'Fashion', subcategory: 'Watches', image: 'https://m.media-amazon.com/images/I/71MQRqCQMtL._UX679_.jpg', stock: 80, rating: 4.3, reviews: 2340, brand: 'Fossil', features: ['Wear OS', 'Heart Rate', 'SpO2', 'GPS'], isActive: true },
  { name: 'Peter England Men Formal Shirt', description: 'Classic formal shirt with regular fit and easy care fabric.', price: 1299, originalPrice: 1999, discount: 35, category: 'Fashion', subcategory: 'Shirts', image: 'https://m.media-amazon.com/images/I/61bKJEiJ5mL._UX679_.jpg', stock: 300, rating: 4.0, reviews: 8900, brand: 'Peter England', features: ['Regular fit', 'Easy care', 'Full sleeves'], isActive: true },
  { name: 'Puma Women Running Shoes', description: 'Lightweight running shoes with cushioned midsole and breathable upper.', price: 3499, originalPrice: 5999, discount: 42, category: 'Fashion', subcategory: 'Footwear', image: 'https://m.media-amazon.com/images/I/71bAMhDY9wL._UX695_.jpg', stock: 180, rating: 4.2, reviews: 4560, brand: 'Puma', features: ['Lightweight', 'Cushioned', 'Breathable'], isActive: true },
  { name: 'US Polo Assn Men Polo T-Shirt', description: 'Classic polo t-shirt with signature embroidered logo and ribbed collar.', price: 999, originalPrice: 1899, discount: 47, category: 'Fashion', subcategory: 'T-Shirts', image: 'https://m.media-amazon.com/images/I/61hh4tbYLpL._UX679_.jpg', stock: 400, rating: 4.0, reviews: 12340, brand: 'US Polo', features: ['Cotton blend', 'Ribbed collar', 'Embroidered logo'], isActive: true },
  { name: 'Titan Analog Watch for Women', description: 'Elegant analog watch with rose gold case and leather strap.', price: 4995, originalPrice: 7495, discount: 33, category: 'Fashion', subcategory: 'Watches', image: 'https://m.media-amazon.com/images/I/71qlRyGb1qL._UY879_.jpg', stock: 100, rating: 4.4, reviews: 5670, brand: 'Titan', features: ['Analog', 'Rose Gold', 'Leather Strap'], isActive: true },

  // Books
  { name: 'Atomic Habits by James Clear', description: 'The #1 New York Times bestseller. Transform your life with tiny changes.', price: 399, originalPrice: 799, discount: 50, category: 'Books', subcategory: 'Self-Help', image: 'https://m.media-amazon.com/images/I/91bYsX41DVL._SY466_.jpg', stock: 500, rating: 4.7, reviews: 156000, brand: 'Penguin', features: ['Bestseller', 'Self-Help', 'Habits'], isActive: true, badge: '#1 Best Seller' },
  { name: 'The Psychology of Money by Morgan Housel', description: 'Timeless lessons on wealth, greed, and happiness.', price: 299, originalPrice: 499, discount: 40, category: 'Books', subcategory: 'Finance', image: 'https://m.media-amazon.com/images/I/71TRUbzcvaL._SY466_.jpg', stock: 400, rating: 4.6, reviews: 89000, brand: 'Harriman House', features: ['Finance', 'Bestseller', 'Psychology'], isActive: true },
  { name: 'Rich Dad Poor Dad by Robert Kiyosaki', description: 'What the rich teach their kids about money that the poor and middle class do not.', price: 299, originalPrice: 499, discount: 40, category: 'Books', subcategory: 'Finance', image: 'https://m.media-amazon.com/images/I/81BE7eeKzAL._SY466_.jpg', stock: 600, rating: 4.5, reviews: 234000, brand: 'Plata Publishing', features: ['Finance', 'Classic', 'Bestseller'], isActive: true },
  { name: 'The Alchemist by Paulo Coelho', description: 'A magical fable about following your dream.', price: 299, originalPrice: 399, discount: 25, category: 'Books', subcategory: 'Fiction', image: 'https://m.media-amazon.com/images/I/51Z0nLAfLmL._SY466_.jpg', stock: 450, rating: 4.6, reviews: 189000, brand: 'HarperOne', features: ['Fiction', 'Classic', 'Inspirational'], isActive: true },
  { name: 'Ikigai: The Japanese Secret to a Long and Happy Life', description: 'Discover the Japanese concept of finding your purpose.', price: 249, originalPrice: 450, discount: 45, category: 'Books', subcategory: 'Self-Help', image: 'https://m.media-amazon.com/images/I/81l3rZK4lnL._SY466_.jpg', stock: 350, rating: 4.4, reviews: 67000, brand: 'Penguin', features: ['Self-Help', 'Japanese Philosophy'], isActive: true },
  { name: 'Sapiens: A Brief History of Humankind by Yuval Noah Harari', description: 'A groundbreaking narrative of humanitys creation and evolution.', price: 399, originalPrice: 799, discount: 50, category: 'Books', subcategory: 'Non-Fiction', image: 'https://m.media-amazon.com/images/I/713jIoMO3UL._SY466_.jpg', stock: 300, rating: 4.6, reviews: 78000, brand: 'Vintage', features: ['History', 'Non-Fiction', 'Bestseller'], isActive: true },

  // Home & Kitchen
  { name: 'Dyson V15 Detect Cordless Vacuum Cleaner', description: 'Laser reveals invisible dust with piezo sensor that counts particles.', price: 62900, originalPrice: 72900, discount: 14, category: 'Home & Kitchen', subcategory: 'Vacuum Cleaners', image: 'https://m.media-amazon.com/images/I/61KNXhtPbKL._SX679_.jpg', stock: 25, rating: 4.6, reviews: 4560, brand: 'Dyson', features: ['Laser Detect', '60min Runtime', 'HEPA'], isActive: true },
  { name: 'Samsung 253L Frost Free Double Door Refrigerator', description: 'Digital Inverter Technology with All-around Cooling and Convertible 5-in-1.', price: 26990, originalPrice: 35990, discount: 25, category: 'Appliances', subcategory: 'Refrigerators', image: 'https://m.media-amazon.com/images/I/71K3HIc8aJL._SX679_.jpg', stock: 40, rating: 4.3, reviews: 8970, brand: 'Samsung', features: ['Digital Inverter', 'Frost Free', 'Convertible'], isActive: true },
  { name: 'Hawkins Stainless Steel Pressure Cooker 5L', description: 'Premium stainless steel pressure cooker with induction compatible base.', price: 2499, originalPrice: 3499, discount: 29, category: 'Home & Kitchen', subcategory: 'Cookware', image: 'https://m.media-amazon.com/images/I/71uVA89FKTL._SX679_.jpg', stock: 200, rating: 4.5, reviews: 45670, brand: 'Hawkins', features: ['5L Capacity', 'Stainless Steel', 'Induction Compatible'], isActive: true },
  { name: 'Pigeon Non-Stick Cookware Set 7 Pcs', description: 'Complete cookware set with non-stick coating and glass lids.', price: 1499, originalPrice: 2999, discount: 50, category: 'Home & Kitchen', subcategory: 'Cookware', image: 'https://m.media-amazon.com/images/I/71KJV1fKmjL._SX679_.jpg', stock: 150, rating: 4.1, reviews: 23450, brand: 'Pigeon', features: ['7 Pieces', 'Non-Stick', 'Glass Lids'], isActive: true },
  { name: 'Solimo 100% Cotton Double Bedsheet', description: '100% cotton bedsheet with 2 pillow covers, 144 thread count.', price: 799, originalPrice: 1499, discount: 47, category: 'Home & Kitchen', subcategory: 'Bedding', image: 'https://m.media-amazon.com/images/I/81xp7JKAH4L._SX679_.jpg', stock: 300, rating: 4.0, reviews: 56780, brand: 'Solimo', features: ['100% Cotton', '2 Pillow Covers', '144 TC'], isActive: true },
  { name: 'Butterfly Glass Top Gas Stove 3 Burner', description: 'Toughened glass top gas stove with brass burners and spill tray.', price: 3999, originalPrice: 5999, discount: 33, category: 'Home & Kitchen', subcategory: 'Gas Stoves', image: 'https://m.media-amazon.com/images/I/61qL2qLvVdL._SX679_.jpg', stock: 100, rating: 4.3, reviews: 12340, brand: 'Butterfly', features: ['3 Burner', 'Glass Top', 'Brass Burners'], isActive: true },
  { name: 'Milton Thermosteel Flask 1000ml', description: 'Vacuum insulated stainless steel flask keeps beverages hot or cold for 24 hours.', price: 799, originalPrice: 1299, discount: 39, category: 'Home & Kitchen', subcategory: 'Bottles', image: 'https://m.media-amazon.com/images/I/61tL8H9zUBL._SX679_.jpg', stock: 250, rating: 4.4, reviews: 34560, brand: 'Milton', features: ['1000ml', '24hr Insulation', 'Stainless Steel'], isActive: true },
  { name: 'Borosil Glass Lunch Box Set of 4', description: 'Microwave safe borosilicate glass containers with leak-proof lids.', price: 1299, originalPrice: 1999, discount: 35, category: 'Home & Kitchen', subcategory: 'Storage', image: 'https://m.media-amazon.com/images/I/71V0SQA2lYL._SX679_.jpg', stock: 180, rating: 4.3, reviews: 8970, brand: 'Borosil', features: ['Set of 4', 'Microwave Safe', 'Leak-Proof'], isActive: true },

  // Computers
  { name: 'Apple MacBook Air M3 Chip 13.6" Laptop', description: 'Supercharged by M3 chip with 18-hour battery life and stunning Liquid Retina display.', price: 114900, originalPrice: 119900, discount: 4, category: 'Computers', subcategory: 'Laptops', image: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SX679_.jpg', stock: 30, rating: 4.7, reviews: 890, brand: 'Apple', features: ['M3 Chip', '18hr Battery', 'Liquid Retina'], isActive: true },
  { name: 'Dell Inspiron 15 Laptop Intel i5 12th Gen', description: '15.6" FHD laptop with Intel Core i5-1235U, 8GB RAM, and 512GB SSD.', price: 54990, originalPrice: 69990, discount: 21, category: 'Computers', subcategory: 'Laptops', image: 'https://m.media-amazon.com/images/I/71jG+e7roXL._SX679_.jpg', stock: 60, rating: 4.2, reviews: 4560, brand: 'Dell', features: ['i5-1235U', '8GB RAM', '512GB SSD'], isActive: true },
  { name: 'ASUS ROG Strix G16 Gaming Laptop', description: 'Gaming laptop with Intel Core i7-13650HX, RTX 4060, and 165Hz display.', price: 129990, originalPrice: 149990, discount: 13, category: 'Computers', subcategory: 'Gaming Laptops', image: 'https://m.media-amazon.com/images/I/81GrCeuCzxL._SX679_.jpg', stock: 25, rating: 4.5, reviews: 1230, brand: 'ASUS', features: ['i7-13650HX', 'RTX 4060', '165Hz'], isActive: true },
  { name: 'Logitech MX Keys Wireless Keyboard', description: 'Advanced wireless keyboard with smart backlighting and Easy-Switch.', price: 12995, originalPrice: 14995, discount: 13, category: 'Computers', subcategory: 'Keyboards', image: 'https://m.media-amazon.com/images/I/71gOLjpVLbL._SX679_.jpg', stock: 100, rating: 4.5, reviews: 5670, brand: 'Logitech', features: ['Backlit', 'Multi-Device', 'USB-C'], isActive: true },
  { name: 'Logitech MX Master 3S Wireless Mouse', description: 'Advanced wireless mouse with 8K DPI sensor and quiet clicks.', price: 9995, originalPrice: 11995, discount: 17, category: 'Computers', subcategory: 'Mice', image: 'https://m.media-amazon.com/images/I/61ni3t1ryQL._SX679_.jpg', stock: 120, rating: 4.7, reviews: 7890, brand: 'Logitech', features: ['8K DPI', 'Quiet Clicks', 'USB-C'], isActive: true },
  { name: 'LG UltraGear 27" QHD Gaming Monitor 165Hz', description: '27" QHD gaming monitor with 165Hz refresh rate, 1ms response time, and G-Sync.', price: 24999, originalPrice: 34999, discount: 29, category: 'Computers', subcategory: 'Monitors', image: 'https://m.media-amazon.com/images/I/81MP2t-pdOL._SX679_.jpg', stock: 50, rating: 4.6, reviews: 3450, brand: 'LG', features: ['165Hz', '1ms', 'G-Sync Compatible'], isActive: true },

  // Gaming
  { name: 'PlayStation 5 Console (Disc Edition)', description: 'Experience lightning-fast loading with ultra-high speed SSD and haptic feedback.', price: 49990, originalPrice: 54990, discount: 9, category: 'Gaming', subcategory: 'Consoles', image: 'https://m.media-amazon.com/images/I/51mWHXY8hyL._SX679_.jpg', stock: 15, rating: 4.8, reviews: 12340, brand: 'Sony', features: ['825GB SSD', '4K Gaming', 'Ray Tracing'], isActive: true },
  { name: 'Sony PS5 DualSense Wireless Controller', description: 'Wireless controller with haptic feedback and adaptive triggers.', price: 5990, originalPrice: 6990, discount: 14, category: 'Gaming', subcategory: 'Controllers', image: 'https://m.media-amazon.com/images/I/61Vo3YBWzEL._SX679_.jpg', stock: 80, rating: 4.7, reviews: 8900, brand: 'Sony', features: ['Haptic Feedback', 'Adaptive Triggers', 'Built-in Mic'], isActive: true },
  { name: 'Razer BlackWidow V4 Pro Gaming Keyboard', description: 'Mechanical gaming keyboard with Razer Green switches and RGB lighting.', price: 22999, originalPrice: 27999, discount: 18, category: 'Gaming', subcategory: 'Keyboards', image: 'https://m.media-amazon.com/images/I/71JqOQjVQRL._SX679_.jpg', stock: 40, rating: 4.5, reviews: 1230, brand: 'Razer', features: ['Mechanical', 'RGB', 'Wrist Rest'], isActive: true },
  { name: 'SteelSeries Aerox 3 Wireless Gaming Mouse', description: 'Ultra-lightweight wireless gaming mouse with 18K DPI sensor.', price: 7999, originalPrice: 10999, discount: 27, category: 'Gaming', subcategory: 'Mice', image: 'https://m.media-amazon.com/images/I/61t+pE0DNCL._SX679_.jpg', stock: 60, rating: 4.4, reviews: 1890, brand: 'SteelSeries', features: ['18K DPI', '68g Weight', '200hr Battery'], isActive: true },
  { name: 'WD Black 4TB Gaming HDD', description: 'High-performance HDD designed for gaming with 7200 RPM and 256MB cache.', price: 9999, originalPrice: 13999, discount: 29, category: 'Gaming', subcategory: 'Storage', image: 'https://m.media-amazon.com/images/I/71Sb2KoZLzL._SX679_.jpg', stock: 70, rating: 4.4, reviews: 4560, brand: 'WD', features: ['4TB', '7200 RPM', '256MB Cache'], isActive: true },
  { name: 'GoPro HERO12 Black Action Camera', description: 'Waterproof action camera with 5.3K60 video and HyperSmooth 6.0.', price: 44990, originalPrice: 49990, discount: 10, category: 'Electronics', subcategory: 'Cameras', image: 'https://m.media-amazon.com/images/I/61p2fow-SBL._SX679_.jpg', stock: 35, rating: 4.5, reviews: 1230, brand: 'GoPro', features: ['5.3K60', 'HyperSmooth 6.0', 'Waterproof'], isActive: true },

  // Sponsored/More Mobiles
  { name: 'Vivo V30 Pro 5G (12GB RAM, 256GB)', description: 'Premium smartphone with ZEISS camera and 120Hz AMOLED display.', price: 46999, originalPrice: 51999, discount: 10, category: 'Electronics', subcategory: 'Mobiles', image: 'https://m.media-amazon.com/images/I/71Zb7x0oCML._SX679_.jpg', stock: 80, rating: 4.2, reviews: 1230, brand: 'Vivo', features: ['ZEISS Camera', '120Hz AMOLED', '80W Charging'], isActive: true },
  { name: 'OPPO Reno11 Pro 5G (12GB RAM, 256GB)', description: 'Portrait expert with 50MP triple camera and 80W SuperVOOC charging.', price: 39999, originalPrice: 44999, discount: 11, category: 'Electronics', subcategory: 'Mobiles', image: 'https://m.media-amazon.com/images/I/71Nj9qykmRL._SX679_.jpg', stock: 90, rating: 4.1, reviews: 890, brand: 'OPPO', features: ['50MP Triple Camera', '80W SuperVOOC', 'ColorOS 14'], isActive: true },
  { name: 'Motorola Edge 50 Pro 5G (12GB RAM)', description: 'Premium edge-to-edge display with 125W TurboPower charging.', price: 35999, originalPrice: 39999, discount: 10, category: 'Electronics', subcategory: 'Mobiles', image: 'https://m.media-amazon.com/images/I/51Hs3JiCq9L._SX679_.jpg', stock: 70, rating: 4.3, reviews: 1560, brand: 'Motorola', features: ['125W TurboPower', 'pOLED Display', '50MP OIS'], isActive: true },
  { name: 'Realme 12 Pro+ 5G (12GB RAM, 256GB)', description: 'Periscope telephoto camera with 3x optical zoom and 120Hz curved display.', price: 29999, originalPrice: 34999, discount: 14, category: 'Electronics', subcategory: 'Mobiles', image: 'https://m.media-amazon.com/images/I/71lL5AODqAL._SX679_.jpg', stock: 100, rating: 4.3, reviews: 1890, brand: 'Realme', features: ['Periscope Camera', '120Hz Curved', '67W Charging'], isActive: true },
  { name: 'Realme Narzo 70 Pro 5G (8GB RAM)', description: 'Dimensity 7050 powered gaming phone with 50MP Sony camera.', price: 18999, originalPrice: 21999, discount: 14, category: 'Electronics', subcategory: 'Mobiles', image: 'https://m.media-amazon.com/images/I/71H0G+zNTBL._SX679_.jpg', stock: 150, rating: 4.2, reviews: 2340, brand: 'Realme', features: ['Dimensity 7050', '50MP Sony', '67W Charging'], isActive: true },
  { name: 'Samsung Galaxy A55 5G (8GB RAM, 256GB)', description: 'Awesome display with 120Hz Super AMOLED and IP67 rating.', price: 39999, originalPrice: 45999, discount: 13, category: 'Electronics', subcategory: 'Mobiles', image: 'https://m.media-amazon.com/images/I/71RJZcb9rPL._SX679_.jpg', stock: 80, rating: 4.3, reviews: 1670, brand: 'Samsung', features: ['120Hz Super AMOLED', 'IP67', '50MP OIS'], isActive: true },

  // TVs
  { name: 'LG 55" 4K Ultra HD Smart OLED TV', description: 'Perfect Black with self-lit OLED pixels, α9 AI Processor, and Dolby Vision.', price: 119990, originalPrice: 159990, discount: 25, category: 'Electronics', subcategory: 'TVs', image: 'https://m.media-amazon.com/images/I/81lACTkCOeL._SX679_.jpg', stock: 20, rating: 4.4, reviews: 1230, brand: 'LG', features: ['OLED', '4K', 'α9 AI', 'Dolby Vision'], isActive: true },
  { name: 'Sony Bravia 65" 4K LED Google TV', description: 'Triluminos Pro display with X1 processor and Google TV built-in.', price: 89990, originalPrice: 109990, discount: 18, category: 'Electronics', subcategory: 'TVs', image: 'https://m.media-amazon.com/images/I/81lACTkCOeL._SX679_.jpg', stock: 25, rating: 4.5, reviews: 2340, brand: 'Sony', features: ['4K LED', 'Google TV', 'X1 Processor', 'Triluminos Pro'], isActive: true },
  { name: 'Samsung 55" Crystal 4K UHD Smart TV', description: 'Crystal Processor 4K with Dynamic Crystal Color and Smart Hub.', price: 44990, originalPrice: 59990, discount: 25, category: 'Electronics', subcategory: 'TVs', image: 'https://m.media-amazon.com/images/I/81lACTkCOeL._SX679_.jpg', stock: 35, rating: 4.3, reviews: 5670, brand: 'Samsung', features: ['Crystal 4K', 'Smart Hub', 'Gaming Mode'], isActive: true },
];

export async function POST() {
  try {
    await connectDB();

    await Product.deleteMany({});

    const products = await Product.insertMany(sampleProducts);

    return NextResponse.json({
      success: true,
      message: `Seeded ${products.length} products successfully!`,
      count: products.length,
    });
  } catch (error: unknown) {
    console.error('Seed error:', error);
    const errorMessage = error instanceof Error ? error.message : 'Failed to seed products';
    return NextResponse.json(
      { success: false, message: errorMessage },
      { status: 500 }
    );
  }
}

export async function GET() {
  return NextResponse.json({
    message: 'Use POST to seed the database with products',
    endpoint: '/api/products/seed',
  });
}
